module.exports.textToSpeechService = require('./textToSpeech.service')
module.exports.authService = require('./auth.service')
module.exports.tokenService = require('./token.service')
module.exports.historyService = require('./history.service')
module.exports.userService = require('./user.service')
module.exports.otpService = require('./otp.service')